kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "test-spring-cloud.fullname" . }}"
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "configmaps", "endpoints" ]
    verbs: [ "get", "list", "watch" ]