kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "test-spring-cloud.fullname" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "test-spring-cloud.serviceAccountName" . }}"
    apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "test-spring-cloud.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io
